language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install . --use-mirrors"
  - "pip install -r tests/requirements.pip --use-mirrors"
  - "pip install -r requirements.pip --use-mirrors"
script: python setup.py test
