language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - "pip install -r tests/requirements.pip --use-mirrors"
  - "pip install -r requirements.pip --use-mirrors"
  - "python setup.py develop"
script: python setup.py test
